name: Debug Secrets Workflow

on:
  workflow_dispatch: # Allows us to run it manually

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to read the test secret
        # This step runs a simple command-line script.
        # It checks if the secret we created has any value.
        run: |
          if [ -z "${{ secrets.TEST_SECRET }}" ]; then
            echo "Error: TEST_SECRET is empty or not found."
            exit 1
          else
            echo "Success! The secret was found and its value is: ${{ secrets.TEST_SECRET }}"
          fi
