name: Send Daily Newsletter

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run newsletter script
        run: node scripts/send-newsletter.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}